-- DopaGut 65 个成就定义 INSERT（v2 修正版）
-- 先执行：DELETE FROM achievement_definitions;
-- 然后执行以下 INSERT

INSERT INTO achievement_definitions (id, title_zh, title_en, description_zh, description_en, icon, rarity, categories, target_value, bg_theme) VALUES
-- 🕐 时间类（12 个）
('early_bird', '早起鸟', 'Early Bird', '在清晨 5:00-7:00 之间完成记录。', 'Record between 5:00-7:00 AM.', '🐦', 'common', '{"time","daily"}', 1, 'bg-dopa-yellow'),
('midnight_owl', '深夜幽灵', 'Midnight Owl', '在凌晨 0:00-4:00 之间完成记录。', 'Record between 0:00-4:00 AM.', '🦉', 'rare', '{"time","daily"}', 1, 'bg-black'),
('lunch_break', '午间摸鱼', 'Lunch Break', '在 11:30-13:30 之间摸鱼投弹。', 'Sneak a drop during lunch break (11:30-13:30).', '🍱', 'common', '{"time","daily"}', 1, 'bg-dopa-cyan'),
('rush_hour', '早高峰战士', 'Rush Hour', '在早高峰 7:00-9:00 之间完成记录。', 'Record during rush hour (7:00-9:00 AM).', '🚇', 'common', '{"time","daily"}', 1, 'bg-dopa-orange'),
('teatime', '下午茶时光', 'Teatime', '在 15:00-16:00 之间完成记录。', 'Record during teatime (15:00-16:00).', '🍵', 'common', '{"time"}', 1, 'bg-dopa-lime'),
('weekend_warrior', '周末战士', 'Weekend Warrior', '在周末累计记录 5 次。', 'Record 5 times on weekends.', '🏖️', 'rare', '{"time","stat"}', 5, 'bg-dopa-cyan'),
('monday_blues', '周一综合症', 'Monday Blues', '周一累计记录 3 次。', 'Record 3 times on Mondays.', '😩', 'rare', '{"time","stat"}', 3, 'bg-dopa-blue'),
('new_year_drop', '跨年之💩', 'New Year Drop', '在 1 月 1 日完成记录。', 'Record on January 1st.', '🎆', 'legendary', '{"time","special"}', 1, 'bg-dopa-purple'),
('double_eleven', '双十一', '11.11 Drop', '在 11 月 11 日完成记录。', 'Record on November 11th.', '🛒', 'rare', '{"time","special"}', 1, 'bg-dopa-pink'),
('valentine', '有情人', 'Valentine Dump', '在 2 月 14 日完成记录。', 'Record on Valentine''s Day.', '💕', 'rare', '{"time","special"}', 1, 'bg-dopa-pink'),
('christmas_gift', '圣诞礼物', 'Christmas Gift', '在 12 月 25 日完成记录。', 'Record on Christmas Day.', '🎄', 'rare', '{"time","special"}', 1, 'bg-dopa-lime'),
('april_fools', '愚人节玩笑', 'April Fools', '在 4 月 1 日完成记录。', 'Record on April Fools'' Day.', '🃏', 'rare', '{"time","hidden"}', 1, 'bg-dopa-yellow'),
-- ⏱️ 时长/速度类（12 个）
('thinker', '思想者', 'Thinker', '累计 5 次单次会话超过 5 分钟。', '5 sessions over 5 minutes.', '🤔', 'rare', '{"stat"}', 5, 'bg-dopa-blue'),
('fall_bean', '速通者', 'Speedrunner', '在 30-60 秒内解决战斗！', 'Finish within 30-60 seconds!', '🫘', 'common', '{"stat"}', 1, 'bg-dopa-pink'),
('flash', '闪电侠', 'The Flash', '30 秒内闪电完成。', 'Finish within 30 seconds.', '⚡', 'rare', '{"stat"}', 1, 'bg-dopa-yellow'),
('path_of_pain', '苦痛之路', 'Path of Pain', '在马桶上坐了整整 15 分钟……', 'You sat for 15 full minutes...', '💀', 'rare', '{"stat","special"}', 1, 'bg-black'),
('philosopher', '哲学家', 'Philosopher', '单次超 30 分钟，你在思考人生。', 'Over 30 minutes. Deep thoughts.', '📖', 'legendary', '{"stat","special"}', 1, 'bg-dopa-purple'),
('speed_demon', '极速恶魔', 'Speed Demon', '累计 5 次 sonic 速度。', '5 sonic speed records.', '👹', 'rare', '{"stat"}', 5, 'bg-dopa-orange'),
('slow_life', '慢生活主义', 'Slow Life', '累计 5 次 slow 速度。', '5 slow speed records.', '🐌', 'rare', '{"stat"}', 5, 'bg-dopa-lime'),
('hex_a_gone', '六边形战士', 'Hex-A-Gone', '速度适中 + 产量适中 + Bristol 4，完美平衡。', 'Normal speed + medium amount + Bristol 4. Balance.', '🔷', 'rare', '{"stat","special"}', 1, 'bg-dopa-cyan'),
('consistent_timer', '精准打卡', 'Consistent Timer', '连续 3 次时长差异小于 30 秒。', '3 consecutive records within 30s of each other.', '⏰', 'legendary', '{"stat","hidden"}', 1, 'bg-dopa-purple'),
('sonic_trio', '音速三连', 'Sonic Trio', '连续 3 次速度为 sonic。', '3 consecutive sonic speed records.', '🏎️', 'rare', '{"stat"}', 1, 'bg-dopa-pink'),
('two_minute_master', '两分钟大师', '2-Min Master', '累计 10 次在 1-2 分钟内完成。', '10 records between 1-2 minutes.', '✌️', 'common', '{"stat"}', 10, 'bg-dopa-yellow'),
('endurance_king', '耐力之王', 'Endurance King', '累计 3 次超过 10 分钟。', '3 records over 10 minutes.', '🏋️', 'common', '{"stat"}', 3, 'bg-dopa-orange'),
-- 💩 Bristol 收集类（8 个）
('bristol_king', '布氏大满贯', 'Bristol King', '集齐全部 7 种 Bristol 类型。', 'Collect all 7 Bristol types.', '👑', 'legendary', '{"collection","special"}', 7, 'bg-dopa-purple'),
('iridium_quality', '铱星！', 'Iridium Quality', 'Bristol 4——完美的香蕉形态 ⭐', 'Bristol 4 — Perfect banana form ⭐', '⭐', 'common', '{"collection"}', 1, 'bg-dopa-yellow'),
('banana_fan', '香蕉狂热', 'Banana Fan', '累计 10 次 Bristol 4。', '10 Bristol type 4 records.', '🍌', 'common', '{"collection","stat"}', 10, 'bg-dopa-yellow'),
('rock_solid', '硬核选手', 'Rock Solid', 'Bristol 1——坚如磐石。', 'Bristol 1 — Hard as rock.', '🪨', 'common', '{"collection"}', 1, 'bg-gray-400'),
('slime_climb', '水涨爬高', 'Slime Climb', '水状来袭，小心脚下！', 'Watery tide incoming! Watch your step!', '🟢', 'common', '{"collection"}', 1, 'bg-dopa-lime'),
('soft_serve', '冰淇淋机', 'Soft Serve', 'Bristol 6——糊状，但不失优雅。', 'Bristol 6 — Mushy but graceful.', '🍦', 'common', '{"collection"}', 1, 'bg-dopa-pink'),
('healthy_streak', '健康连击', 'Healthy Streak', '连续 5 次 Bristol 3/4/5（健康范围）。', '5 consecutive Bristol 3/4/5 (healthy range).', '💚', 'rare', '{"collection","stat"}', 5, 'bg-dopa-lime'),
('extreme_collector', '两极分化', 'Extreme Collector', '同时拥有 Bristol 1 和 7 的记录。', 'Have both Bristol 1 and 7 in history.', '🔀', 'rare', '{"collection","hidden"}', 1, 'bg-dopa-purple'),
-- 🎨 颜色收集类（8 个）
('color_collector', '色彩收藏家', 'Color Collector', '累计记录过 4 种不同的颜色。', 'Collect 4 different colors.', '🎨', 'rare', '{"collection"}', 4, 'bg-dopa-yellow'),
('rainbow_master', '彩虹大师', 'Rainbow Master', '集齐全部 7 种颜色。', 'Collect all 7 colors.', '🌈', 'legendary', '{"collection","special"}', 7, 'bg-dopa-purple'),
('golden_pumpkin', '黄金南瓜', 'Golden Pumpkin', '黄金色——灵魂之夜的稀有奖品。', 'Golden — A rare Spirit''s Eve prize.', '🎃', 'common', '{"collection"}', 1, 'bg-dopa-orange'),
('code_red', '红色警报', 'Code Red', '记录一次 red，请注意健康。', 'Record a red. Please monitor your health.', '🚨', 'rare', '{"collection"}', 1, 'bg-dopa-pink'),
('void_heart', '虚空之心', 'Void Heart', '黑色……来自深渊最深处。', 'Black... from the deepest abyss.', '🖤', 'common', '{"collection"}', 1, 'bg-black'),
('green_goblin', '绿巨人', 'Green Goblin', '累计 3 次 green 颜色。', '3 green color records.', '🥬', 'common', '{"collection"}', 3, 'bg-dopa-lime'),
('fifty_shades', '五十度棕', '50 Shades of Brown', '累计 20 次 brown 颜色。', '20 brown color records.', '🟤', 'common', '{"collection","stat"}', 20, 'bg-dopa-orange'),
('pale_rider', '苍白骑士', 'Pale Rider', '记录一次 pale 颜色。', 'Record a pale color.', '🦴', 'rare', '{"collection"}', 1, 'bg-gray-400'),
-- 😈 心情类（10 个）
('zen_master', '禅定大师', 'Zen Master', '心情禅定且时长超过 5 分钟。', 'Mood Zen and duration over 5 minutes.', '🧘', 'rare', '{"vibe","special"}', 1, 'bg-dopa-lime'),
('nuclear_blast', '核爆现场', 'Nuclear Blast', '正如其名，这是一场核爆。', 'As the name suggests, a nuclear explosion.', '☢️', 'common', '{"vibe"}', 1, 'bg-dopa-orange'),
('spicy_lover', '辣味爱好者', 'Spicy Lover', '心情火辣辣，且 Bristol 类型偏硬。', 'Spicy mood and hard Bristol type.', '🔥', 'common', '{"vibe"}', 1, 'bg-dopa-yellow'),
('mood_collector', '情绪收藏家', 'Mood Collector', '集齐 7 种不同心情。', 'Collect 7 different moods.', '🎭', 'rare', '{"vibe","collection"}', 7, 'bg-dopa-cyan'),
('mood_master', '情绪大师', 'Mood Master', '集齐全部 10 种心情。', 'Collect all 10 moods.', '🃏', 'legendary', '{"vibe","collection"}', 10, 'bg-dopa-purple'),
('happy_camper', '快乐露营者', 'Happy Camper', '累计 5 次 happy 心情。', '5 happy mood records.', '😊', 'common', '{"vibe"}', 5, 'bg-dopa-yellow'),
('struggle_bus', '痛苦面具', 'Struggle Bus', '累计 3 次 struggle 心情。', '3 struggle mood records.', '😤', 'common', '{"vibe"}', 3, 'bg-gray-400'),
('pain_veteran', '久经沙场', 'Pain Veteran', '累计 5 次 pain 心情。', '5 pain mood records.', '😖', 'rare', '{"vibe"}', 5, 'bg-dopa-pink'),
('classic_man', '经典老炮', 'Classic Man', '累计 10 次 classic 心情。', '10 classic mood records.', '💩', 'common', '{"vibe","stat"}', 10, 'bg-dopa-purple'),
('holy_water', '圣水', 'Holy Water', '累计 3 次 spray 心情。', '3 spray mood records.', '💧', 'common', '{"vibe"}', 3, 'bg-dopa-blue'),
-- 📊 里程碑类（10 个）
('fiber_freak', '纤维狂人', 'Fiber Freak', '连续 3 天保持排便记录。', 'Consistent drops for 3 consecutive days.', '🥦', 'common', '{"daily","stat"}', 3, 'bg-dopa-cyan'),
('qualified', '达标啦！', 'Qualified!', '恭喜，你成功投下了第一颗💩', 'Congrats! You made your first drop 💩', '✅', 'common', '{"stat"}', 1, 'bg-dopa-lime'),
('ten_timer', '十全十美', 'Ten Timer', '累计 10 次记录。', '10 total records.', '🔟', 'common', '{"stat"}', 10, 'bg-dopa-cyan'),
('half_century', '半百之路', 'Half Century', '累计 50 次记录。', '50 total records.', '🏅', 'rare', '{"stat"}', 50, 'bg-dopa-yellow'),
('heart_kill', '腐化之心', 'Heart Kill', '累计 100 次记录——你击败了最终 Boss。', '100 total records — You defeated the final boss.', '❤️‍🔥', 'legendary', '{"stat","special"}', 100, 'bg-dopa-pink'),
('grand_master', '大师之路', 'Grand Master', '累计 500 次记录。', '500 total records.', '🏆', 'legendary', '{"stat","special"}', 500, 'bg-dopa-purple'),
('ascension_20', '攀登者Lv.20', 'Ascension 20', '连续 7 天有记录——每天都在攀升。', '7 consecutive days with records.', '⬆️', 'rare', '{"daily","stat"}', 7, 'bg-dopa-orange'),
('monthly_iron', '铁人月卡', 'Monthly Iron', '连续 30 天有记录。', '30 consecutive days with records.', '🔥', 'legendary', '{"daily","stat"}', 30, 'bg-dopa-orange'),
('team_round', '最佳拍档', 'DUOS!', '同一天记录 2 次以上。', 'Record more than twice in one day.', '🤝', 'common', '{"daily"}', 1, 'bg-dopa-cyan'),
('triple_threat', '帽子戏法', 'Triple Threat', '同一天记录 3 次以上。', 'Record more than 3 times in one day.', '🎩', 'rare', '{"daily","stat"}', 1, 'bg-dopa-purple'),
-- 🏆 隐藏/组合类（5 个+1 个 meta）
('ghost_poop', '幽灵便便', 'Ghost Poop', '在冲水之前它就消失了。', 'It vanishes before you even flush.', '👻', 'legendary', '{"hidden"}', 1, 'bg-dopa-purple'),
('perfect_run', '完美一投', 'Perfect Run', 'Bristol 4 + brown + happy + medium + normal，天选之人。', 'B4 + brown + happy + medium + normal. Perfection.', '🌟', 'legendary', '{"hidden","special"}', 1, 'bg-dopa-yellow'),
('lucky_dog', '我真幸运', 'Lucky Dog', '超过 2 天没有记录后终于拉出来了……苦尽甘来！', 'Finally dropped after 2+ days of nothing... Worth the wait!', '🕸️', 'rare', '{"hidden"}', 1, 'bg-black'),
('mega_blast', '妈妈的炸弹！', 'MEGA MAMA!', 'nuclear + high + sonic + Bristol 7——毁灭一切！', 'Nuclear + high + sonic + B7 — Total destruction!', '💥', 'legendary', '{"hidden","special"}', 1, 'bg-dopa-orange'),
('crown_grabber', '抓握皇冠', 'Crown Grabber', '连续 5 天每天都有记录——日日夺冠！', '5 consecutive days with records — Daily champion!', '👑', 'rare', '{"daily","special"}', 5, 'bg-dopa-yellow'),
('achievement_hunter', '成就猎人', 'Achievement Hunter', '解锁 30 个成就。', 'Unlock 30 achievements.', '🎯', 'rare', '{"special"}', 30, 'bg-dopa-purple');
